<div class="home-wrapper">
    <div class="featured-cats" style="background-color: #f5f5f5; padding: 50px 0 30px;">
        <div class="container-block">
            <div class="cat-title">Find things you'll love. Support independent sellers. Only on
                <img src="{{media url="wysiwyg/logo-content.png"}}" alt="Joomei" width="103" height="34"/>
            </div>
            <ul class="list-nostyle list-cats">
                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-1.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Gift for Men</a>
                        </strong>
                    </div>
                </li>

                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-2.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Hot Clothing</a>
                        </strong>
                    </div>
                </li>

                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-3.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Toy & Play</a>
                        </strong>
                    </div>
                </li>

                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-4.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Art & Collectibles</a>
                        </strong>
                    </div>
                </li>

                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-5.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Home Decor</a>
                        </strong>
                    </div>
                </li>

                <li>
                    <div class="img-cat">
                        <a href="#"><img src="{{media url="wysiwyg/category/cat-6.jpg"}}" alt="Category" width="190" height="190"/></a>
                    </div>

                    <div class="info-cat">
                        <strong>
                            <a href="#">Craft Supplies</a>
                        </strong>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div class="services" style="padding: 60px 0 30px; border-bottom: 1px solid #ddd; margin-bottom: 57px;">
        <div class="container-block">
            <ul class="list-nostyle list-service">
                <li>
                    <div class="sv-title"><strong>UNIQUE EVERYTHING</strong></div>
                    <p>We have millions of one-of-a-kind items, so you can find whatever you want (really want).</p>
                </li>

                <li>
                    <div class="sv-title"><strong>FREE SHIPPING</strong></div>
                    <p>We have millions of one-of-a-kind items, so you can find whatever you want (really want).</p>
                </li>

                <li>
                    <div class="sv-title"><strong>PRICE PROTECTION</strong></div>
                    <p>We have millions of one-of-a-kind items, so you can find whatever you want (really want).</p>
                </li>
            </ul>
        </div>
    </div>

    <div class="block-products">
        <div class="container-block">
            {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="Featured Products" show_pager="0" products_count="5" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`()`,`value`:`T-856201, T-01901365, T-8563214, T-0103983, T-010369, T-0139057, T-8563014, T-7145394`^]^]"}}
        </div>
    </div>

    <div class="group-banner" style="margin-bottom: 27px;">
        <div class="container-block">
            <div class="row">
                <div class="col-lg-6">
                    <div class="banner-image">
                        <a href="#"><img src="{{media url="wysiwyg/banner/banner-1.jpg"}}" alt="Banner" width="630" height="630"/></a>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-6 col-6">
                            <div class="banner-image">
                                <a href="#"><img src="{{media url="wysiwyg/banner/banner-2.jpg"}}" alt="Banner" width="300" height="300"/></a>
                            </div>
                        </div>

                        <div class="col-lg-6 col-6">
                            <div class="banner-image">
                                <a href="#"><img src="{{media url="wysiwyg/banner/banner-3.jpg"}}" alt="Banner" width="300" height="300"/></a>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 col-6">
                            <div class="banner-image">
                                <a href="#"><img src="{{media url="wysiwyg/banner/banner-4.jpg"}}" alt="Banner" width="300" height="300"/></a>
                            </div>
                        </div>

                        <div class="col-lg-6 col-6">
                            <div class="banner-image">
                                <a href="#"><img src="{{media url="wysiwyg/banner/banner-5.jpg"}}" alt="Banner" width="300" height="300"/></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="block-products">
        <div class="container-block">
            {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="Most Popular" show_pager="0" products_count="5" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`()`,`value`:`T-0961523, T-85692145, T-4581369, T-412578, T-4582301, T-0135896, T-4253697, T-8549301`^]^]"}}
        </div>
    </div>

    <div class="banner-full" style="margin-bottom: 55px;">
        <div class="container-block">
            <div class="banner-image">
                <a href="#"><img src="{{media url="wysiwyg/banner/banner-6.jpg"}}" alt="Banner" width="1290" height="320"/></a>
            </div>
        </div>
    </div>

    <div class="why-choose-us" style="margin-bottom: 57px;">
        <div class="container-block">
            <div class="block block-choose-us">
                <div class="block-title title" style="margin-bottom: 15px;">
                    <strong>Why Choose Us</strong>
                </div>

                <div class="block-content">
                    <p>What is a seasoned professional?  If you ask 5 people you will get 5 different answers to your question.  That same rule of thumb rings true for employees and their hiring practices. If you are dealing with a company who has a senior management team made up mostly of individuals in their twenties and thirties, more times than not their hiring...</p>
                    <a href="#">Learn more</a>
                </div>
            </div>
        </div>
    </div>

    <div class="bottom-info" style="margin-bottom: 30px;">
        <div class="container-block">
            <div class="row">
                <div class="col-lg-4 col-12">
                    <div class="info">
                        <strong>In-Store Safety Precautions</strong>
                        <a href="#">Learn more</a>
                    </div>
                </div>

                <div class="col-lg-4 col-12">
                    <div class="info">
                        <strong>Download the Our App now</strong>
                        <a href="#">Learn more</a>
                    </div>
                </div>

                <div class="col-lg-4 col-12">
                    <div class="info">
                        <strong>Checkout  with </strong>
                        <img src="{{media url="wysiwyg/after-pay.png"}}" alt="After Pay" width="118" height="24"/>
                        <a href="#">Learn more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>