Block Title: Theme - Footer Content
Identifier: footer-content
Content:


<div class="footer-top">
    <div class="container-block">
        <div class="newsletter-footer">
            <div class="block-title">Get Our Emails</div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="newsletter-text">Sign up to receive our emails and get first dibs on new arrivals,
                        sales, exclusive content, events and more!
                    </div>
                </div>

                <div class="col-lg-6">
                    {{block class="Magento\Newsletter\Block\Subscribe" template="Magento_Newsletter::subscribe.phtml"}}
                </div>
            </div>

            <div class="newsletter-note">By entering your email address, you agree to receive our offers, promotions,
                other commercial messages. You can view our <a href="#">Privacy Policy</a> here and you may unsubscribe
                at any time.
            </div>
        </div>
    </div>
</div>

<div class="footer-middle">
    <div class="container-block">
        <div class="row">
            <div class="col-lg-3">
                <div class="block-footer">
                    <div class="block-title">About Us</div>
                    <div class="block-content">
                        <ul class="list-nostyle list-footer-links">
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">The Stories</a></li>
                            <li><a href="#">Press</a></li>
                            <li><a href="#">Wholesale</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="block-footer">
                    <div class="block-title">Policy</div>
                    <div class="block-content">
                        <ul class="list-nostyle list-footer-links">
                            <li><a href="#">Return Policy</a></li>
                            <li><a href="#">Terms Of Use</a></li>
                            <li><a href="#">Security</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Sitemap</a></li>
                            <li><a href="#">EPR Compliance</a></li>
                            <li><a href="#">Payment Method</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="block-footer">
                    <div class="block-title">Social</div>
                    <div class="block-content">
                        <ul class="list-nostyle list-footer-links">
                            <li><a href="#">Facebook</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Youtube</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="block-footer">
                    <div class="block-title">Helps</div>
                    <div class="block-content">
                        <ul class="list-nostyle list-footer-links">
                            <li><a href="#">Payments</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Cancellation & Returns</a></li>
                            <li><a href="#">FAQs</a></li>
                            <li><a href="#">Report Infringement</a></li>
                            <li><a href="#">Submit an Idea</a></li>
                            <li><a href="#">Suggest a Product</a></li>
                            <li><a href="#">Directions to Warehouse</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>