Block Title: Theme - Sidebar Top Product Page
Identifier: sidebar-top-detail
Content:

<div class="recently-products">{{widget type="Magento\Catalog\Block\Widget\RecentlyViewed" uiComponent="widget_recently_viewed" page_size="9" show_attributes="image,price" show_buttons="add_to_cart" template="product/widget/viewed/sidebar.phtml"}}
    <div class="recently-all">{{widget type="Magento\Cms\Block\Widget\Page\Link" anchor_text="View All" title="View All" template="widget/link/link_inline.phtml" page_id="5"}}</div>
</div>