<div class="dropdown-search">
    <div class="term-content">
        <ul>
            <li><a href="{{store url=""}}catalogsearch/result/?q=dress">dress</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=shorts">shorts</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=gear">gear</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=craft supplies">craft supplies</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=tank">tank</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=discount">discount</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=jackets">jackets</a></li>
            <li><a href="{{store url=""}}catalogsearch/result/?q=watches">watches</a></li>
        </ul>
    </div>
</div>