<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if ($block->customerLoggedIn()) : ?>
    <li class="customer-welcome">
        <a class="account-link" href="<?php echo $this->getUrl('customer/account') ?>" role="link"
           tabindex="0"
           data-mage-init='{"dropdown":{}}'
           data-toggle="dropdown"
           data-trigger-keypress-button="true"
           data-bind="scope: 'customer'">
            <span class="customer-name">
                <?= $block->escapeHtml(__('Account')) ?>
            </span>
        </a>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if ($block->getChildHtml()) : ?>
            <div class="customer-menu" data-target="dropdown">
                <?= $block->getChildHtml() ?>
            </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
